### ISSUE TITLE
Error when deploying Hyperledger Composer when Hyperledger Fabric is running on Kubernetes

### ISSUE THREAD

**Issue by nicolapaoli** [aidtechnology/nephos#28]
## Summary
Receiving an error when deploying Hyperledger Composer to Kubernetes with running instance of Hyperledger Fabric.

## Detailed Issues
Running command 
```
╰─➤  PYTHONPATH=. ./nephos/deploy.py -f ./examples/prod/nephos_config.yaml composer
```
I receive the following error:
```
peer_ca_msp = opts['cas'][peer_ca]['msp']
KeyError: 'msp'
```

## Possible Fix
Adapt composer deployment to latest structure of`nephos-config.yaml` 

## Environment
- Nephos version `0.1.5`
- Python version `3.7.2`

**Comment by alexvicegrab** [comment]
Addressed by #29
