### ISSUE TITLE
Couldn't find satisfactory requirement with python 3.7

### ISSUE THREAD

**Issue by pikvik** [aidtechnology/nephos#50]
Is nephos non compatible with python 3.7  ? 

<img width="1678" alt="screen shot 2019-02-22 at 1 31 02 pm" src="https://user-images.githubusercontent.com/18361946/53228355-f2f31a00-36a6-11e9-9bb2-fc7a234612f0.png">

**Comment by pikvik** [comment]
Sorry my bad my pip is still running on python 2.7.

**Comment by alexvicegrab** [comment]
Only 3.7 onwards alas. Can't maintain Python 2.7 as it's being phased out.
