### ISSUE TITLE
Document the need for PYTHONPATH=.

### ISSUE THREAD

**Issue by marcelloromani** [aidtechnology/nephos#56]
After following the steps outlined in the README to run Nephos from the git repository, I found that `deploy.py` would complain about not finding module `nephos`

```
$ ./nephos/deploy.py --help

Traceback (most recent call last):
  File "./nephos/deploy.py", line 22, in <module>
    from nephos.runners import (
ModuleNotFoundError: No module named 'nephos'
```

The solution for me was:
```
export PYTHONPATH=$PYTHONPATH:.
```

This is not documented in the README (it only mentions `PYTHONPATH=.` for unit tests).

**Comment by alexvicegrab** [comment]
Noted, I will fix this soon.

**Comment by alexvicegrab** [comment]
Fixed
